title: Dylan Nielson's Homepage
page-top-title: Dylan M. Nielson
top-section-bg-text: Pychiatry, Machine Learning, Methods, and Rock Climbing 
home-subtitle: More info to come
copyright-text: '&copy; Dylan Nielson.'
