title: Dylan Nielson's Homepage
page-top-title: Dylan M. Nielson
top-section-bg-text: Mental Health and Machine Learning, Methods, and Rock Climbing 
home-subtitle: About me
copyright-text: '&copy; Dylan Nielson.'
